"""Change relations.

Revision ID: 1bd1b49eced5
Revises: 4fe7aaf83585
Create Date: 2024-11-02 15:50:58.769635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd1b49eced5'
down_revision = '4fe7aaf83585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
