"""Enum.

Revision ID: 3bb59c98127c
Revises: 434c43bf060b
Create Date: 2024-11-03 13:58:52.668424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb59c98127c'
down_revision = '434c43bf060b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
