"""First migration

Revision ID: 9fc32c1990ad
Revises: 
Create Date: 2024-11-01 23:24:26.536912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import ChoiceType
from app.core.constants import STATUS

# revision identifiers, used by Alembic.
revision = '9fc32c1990ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('status', ChoiceType(STATUS), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('button')
    # ### end Alembic commands ###
